### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by jayb0c** [jakeStoneDev/driving-game#1]
- [x] Create html, css, and js files. Link them
- [x] create a two row layout: One with a title and the other row has a relative div container
- [x] place the car image absolutely onto the relative div
- [x] when looking at the page, the car should be within the proper div with a border. The tile should be above it. It should have display: flex set the the row and items

**Comment by jakeStoneDev** [comment]
- [ ] Create html, css, and js files. Link them
- [ ] create a two row layout: One with a title and the other row has a relative div container
- [ ] place the car image absolutely onto the relative div
- [ ] when looking at the page, the car should be within the proper div with a border. The tile should be above it. It should have display: flex set the the row and items

**Comment by jayb0c** [comment]
User can see custom car on the div with custom background
